---

- hosts: all
  become: yes
  tasks:
  - name: Update apt cache
    apt:
      update_cache: yes
    when: ansible_distribution == "Ubuntu" or ansible_distribution == "Debian"

  - name: Update apk cache
    apk:
      update_cache: yes
    when: ansible_distribution == "Alpine"


